### ISSUE TITLE
mips: R6 (all 32/64 bit, big/little endian) fail to build

### ISSUE THREAD

**Issue by carenas** [zherczeg/sljit#81]
as shown by:

```
In file included from sljit_src/sljitLir.c:2116:
sljit_src/sljitNativeMIPS_common.c: In function 'sljit_emit_cmov':
sljit_src/sljitNativeMIPS_common.c:2212:9: error: 'MOVZ' undeclared (first use in this function)
 2212 |   ins = MOVZ | TA(EQUAL_FLAG);
      |         ^~~~
sljit_src/sljitNativeMIPS_common.c:2212:9: note: each undeclared identifier is reported only once for each function it appears in
sljit_src/sljitNativeMIPS_common.c:2215:9: error: 'MOVN' undeclared (first use in this function)
 2215 |   ins = MOVN | TA(EQUAL_FLAG);
      |         ^~~~
sljit_src/sljitNativeMIPS_common.c:2237:9: error: 'MOVT' undeclared (first use in this function)
 2237 |   ins = MOVT;
      |         ^~~~
sljit_src/sljitNativeMIPS_common.c:2243:9: error: 'MOVF' undeclared (first use in this function)
 2243 |   ins = MOVF;
      |         ^~~~
```

this is a regression since 9afd34d0f97979166b24ff481851d2bf531e2c3f
